### ISSUE TITLE
API errors with Colab notebooks

### ISSUE THREAD

**Issue by J-Fo-S** [DerTarchin/Pix2Pix-Generative-Cities#1]
Hi, neat-looking project. However, I cannot run any of the colab notebooks without getting a 404 when requesting the Google Drive hosted files, despite having successfully entered the auth. Have the files been moved? If so, would greatly appreciate an update so I can see the code in action - many thanks

**Comment by DerTarchin** [comment]
Sorry, this project wasn't intended for others to use as-is, your 404s are probably for various models/checkpoints or datasets. We did not keep them on Drive, so you will have to either train or find your own models! I may upload a more permanent version in the future but for now I have limited space. The dataset is available for download from the original creators, see "Resources" section of the ReadMe. Feel free to modify the colab files to work with your own data/models! Thanks for your interest and comments!
